### ISSUE TITLE
installation problem 2.8

### ISSUE THREAD

**Issue by nafergo** [ranjian0/building_tool#10]
Tried to install 
Modules Installed () from '/home/nafergo/Downloads/building_tool-0.9.2-alpha2.zip' into '/home/nafergo/.config/blender/2.80/scripts/addons'

but but doesn't show in addons list...

**Comment by nafergo** [comment]
If I install using zip from branch theres no problem. Error only comes up with zip from releases.

**Comment by ranjian0** [comment]
The zip releases probably just need an update.

**Comment by ranjian0** [comment]
Updated.
Try Blender2.80 v0.9.3 release.
