### ISSUE TITLE
UV: auto uv unwrap

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#100]
Automatically UV unwrap any face created by Building Tools.

Use Cube Projection - Because all the geometry created by Building Tools is intended for architectural design, we can use Cube Projection.

**Comment by ranjian0** [comment]
This should be optional, give users allowance to do their own unwrap. Was corresponding with user about materials and for his case, `project from view` was the better option.

**Comment by ranjian0** [comment]
Pushed a new branch `feature-uv-unwrap` with implementation of this.

**Comment by ranjian0** [comment]
closed by 6a61dfbc
