### ISSUE TITLE
Create new material from Material Tools

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#101]
While using material tools, there should be an option to create a new material for a facemap.

Currently there is option to select material for a facemap from list of existing materials, but no option to create one.

<img width="202" alt="Screenshot 2020-05-28 at 4 29 39 PM" src="https://user-images.githubusercontent.com/11018027/83133628-c7a87780-a100-11ea-9632-d2eb71447ccf.png">

**Comment by ranjian0** [comment]
Should we really be duplicating functionality that already exists in blender? The burden of material creation and setup is on the user, addon only comes in to simplify assigning materials to the geometry that was generated.

I had already thought about this and decided against it for multiple reasons. 

I also tried having the addon create materials for each facemap. It was also inconvenient.

**Comment by luckykadam** [comment]
I agree with not duplicating functionality. But the current workflow is very non-intuitive and slow.

Right now the steps to assign material is:
1. unselect all faces in viewport
2. select the facemap in Material Tools panel
3. hit "select"
4. in Property Editor, go to material tab
5. add a material slot
6. create a new material
7. click "assign"

This flow is so slow, it needs at least 8 clicks.

**Comment by ranjian0** [comment]
How would a better workflow look like? We should start from there!

**Comment by luckykadam** [comment]
One option is to complete remove the ability to change facemaps from UI. That would let achieve this in fewer steps. One possible workflow is:
1. select the facemap from the list (this should automatically select all the corresponding faces and deselect others)
2. in Property Editor, go to material tab
3. add a material slot
4. create a new material
5. click "assign"

This option reduces the number of clicks from 8 to 5.

**Comment by ranjian0** [comment]
Having automatic selection will interfere with other tools that need selection. At any given point, a facemap is always active. which means some faces will always be selected. If a user wants to add a window, they would need to `de-select all` first inorder to clear current facemap selection and then proceed to select faces where they want windows.

**Comment by luckykadam** [comment]
It's not necessary, that a facemap is always active. Currently, if there is no facemap assigned to the selected face, then there is no facemap selected.
Also we don't need to `de-select all` inorder to clear facemap selection. Clicking on a face would deselect all face but the one clicked on, just like what normally happens.

**Comment by ranjian0** [comment]
> It's not necessary, that a facemap is always active. Currently, if there is no facemap assigned to the selected face, then there is no facemap selected.

After playing a bit with the addon I am not so sure about this. This may be true, but impossible to confirm since:
1. All faces created by building tools belong to some facemap. Even with no face selected, a facemap is always active. 
2. Faces created using blender tools like extrude also seem to inherit facemap of nearby/adjacent faces.
Can you post a screenshot of the situation you are suggesting here?

> Also we don't need to `de-select all` inorder to clear facemap selection. Clicking on a face would deselect all face but the one clicked on, just like what normally happens.

Yep, this is true. Had not thought about this!

**Comment by luckykadam** [comment]
>  Can you post a screenshot of the situation you are suggesting here?

Two situations I can think of are:
1. when you `remove` a facemap from a face
<img width="655" alt="Screenshot 2020-05-31 at 2 33 18 PM" src="https://user-images.githubusercontent.com/11018027/83348676-50ffba00-a34c-11ea-9bc6-cff3cffb0ed3.png">

2. when you use BT on existing mesh


> Yep, this is true. Had not thought about this!

This approach can simplify the material tools a lot.

**Comment by ranjian0** [comment]
Alright then! Feel free to make a pull for this!

**Comment by luckykadam** [comment]
@ranjian0 this is more difficult than it seems. 
I could not find a way to bind `select` action on list item to some function. I think we can leave it as it is, and come back to it after 1.0 release.

**Comment by ranjian0** [comment]
Normally if its a custom list object, you can use the `update` function on the index, But to avoid duplication, I used the already existing `face_maps` UIList in blender.

See `__init__.py` line `76`.

Your right, the only way is to re-implement `face_maps` UIList and add custom functionality

**Comment by ranjian0** [comment]
Add new operator to assign a new material to active facemap.

closed by 7ca93a0d43742ed465da7f5932cb0063055f97c1
