### ISSUE TITLE
interior side support so we can also use it for games

### ISSUE THREAD

**Issue by GameDevBhavesh** [ranjian0/building_tool#102]
**feature request.**
hey i'm an indie game developer want to use it in creating buildings for games and modeling building is so much of hassle 
and i found this awesome add-on but my only problem is i also want interior side of building so player can explore building.

**solution i want.**
i want that along with exterior, interior side will be also generated
don't want extra feature like adding stuff in the interior side like stairs for upper floor as it can also be done manually, but basic interior walls so we don't have to add it manually

**alternative.**
 i don't know is there is any other way to do it with modifiers like solidify i tried it but getting weird results

**Additional context.**
![image](https://user-images.githubusercontent.com/38570988/83326554-8ba51c00-a292-11ea-9bbd-4b584bb4243a.png)

**Comment by ranjian0** [comment]
If I am getting you right, you want a way to generate interior walls?

If you are doing game development, the best solution for this is to have doors and when player goes through, you switch to a different scene/level. This way you can separate exterior and interior scenes.

`Building Tools` is specifically designed for building exteriors only. Accepting this feature will open up a can of worms we are not ready for.

**Comment by ranjian0** [comment]
Closing as out of scope for the addon
