### ISSUE TITLE
Fairly frequent crash around roof edits

### ISSUE THREAD

**Issue by aarongerber** [ranjian0/building_tool#105]
When selecting Flip Direction on a Gable roof Blender can crash

**To Reproduce**
1. Create multiple buildings directly adjacent to each other with different heights
2. Create roofs with the type Gable
3. Make sure Roof Hangs is checked
4. Click Flip Direction

**Expected behaviour**
Roof flips directions... but it doesn't... instead Blender crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version 2.83
 - Addon Version 1.0-beta

**Comment by ranjian0** [comment]
I am currently in the process of making improvements to the roof module for both gable and hip roof. You can track my progress in issue #40.

Since this is a priority bug, I may end up merging the changes before the proposed 1.1.

Thanks for your input.

**Comment by ranjian0** [comment]
I am not able to duplicate the crash. A blend file of your setup would be appreciated.

**Comment by aarongerber** [comment]
I should have attached one. I will try to reproduce this again and upload for you. My environment was multiple multi-story buildings (around 20) next to each other (literally side by side, object against object). Usually the crash occurred when a lower building was below the taller one I was working on.

**Comment by ranjian0** [comment]
pushed new gable roof implementation. Hopefully, this issue is resolved
