### ISSUE TITLE
Window Bar Is Modified When Door Has Panels.

### ISSUE THREAD

**Issue by Qomolangma888** [ranjian0/building_tool#108]
If you set window style is bar and door style is panels or window_panels, then the window bar change from cube shape to triangle shape, this will cause window bars can't be rendered normally.  I think there are some parameters are shared by window bar and door panels, I hope you can pay attention to this bug!
Finally, I like this add_on very much, thanks your hard work.

**Comment by Qomolangma888** [comment]
OK, I will upload the pictures if I have time, thanks your reply!

**Comment by Qomolangma888** [comment]
![Bug_01](https://user-images.githubusercontent.com/31262886/83831565-419cba00-a71a-11ea-9e5c-fd56b757d293.jpg)
![Bug_02](https://user-images.githubusercontent.com/31262886/83831582-4bbeb880-a71a-11ea-814b-44fb451352eb.jpg)
![Bug_03](https://user-images.githubusercontent.com/31262886/83831588-4eb9a900-a71a-11ea-9183-4b544fb2f3cb.jpg)
![Bug_04](https://user-images.githubusercontent.com/31262886/83831595-524d3000-a71a-11ea-967d-bcef823499eb.jpg)
Thanks your hard work again!

**Comment by ranjian0** [comment]
Unable duplicate this.

**Comment by ranjian0** [comment]
Image 3 shows the expected window bars as in image 1.
