### ISSUE TITLE
Clamp invalid values

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#110]
**Describe the bug**
You can set invalid values which cause a weird meshes, for example a frame thickness larger than the door's size.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create building
2. Create door
3. Change frame thickness (or any other variable)

**Expected behaviour**
I expected the values to stay within a range that create good results.

**Comment by ranjian0** [comment]
I agree. This issue is closely related to task #25

**Comment by ranjian0** [comment]
Transfered to parent issue #25.
