### ISSUE TITLE
Stairs don't generate at ground level by default

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#111]
**Describe the bug**
They generate floating, in nearly all cases you want it to be on the ground level so moving it depending on it's total height would be a great feature! This could be done by just controlling the top of the stairs and letting them go all the way down to the ground just like doors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create building
2. Create stairs

**Expected behaviour**
Stairs going to the ground not flying

**Comment by MCrafterzz** [comment]
Also affects balconies

**Comment by ranjian0** [comment]
Would appreciate screenshot of the issue!

**Comment by MCrafterzz** [comment]
> Would appreciate screenshot of the issue!

![image](https://user-images.githubusercontent.com/19669673/83847563-c5e84080-a70c-11ea-915a-960ed618f208.png)

**Comment by ranjian0** [comment]
Perhaps @luckykadam should clarify exactly how his design for balcony and stairs is intended to be used.

Personally, I agree with you about the location where the stairs should default to. I am not so sure about the stair count option though.

My original idea for stairs and balcony was that they would only be created on the slab faces. Unfortunately, this was not obvious to users and led to weird results. in contrast, the current design provides too much freedom.

**Comment by luckykadam** [comment]
Yes, it is intended to be used on `slab` faces.

To make it clear, we can enable subset of operations based on selected face's facemap.

**Comment by MCrafterzz** [comment]
> Yes, it is intended to be used on `slab` faces.
> 
> To make it clear, we can enable subset of operations based on selected face's facemap.

Many buildings don't have the slabs so shouldn't you be able to create stairs in that case?

**Comment by MCrafterzz** [comment]
@ranjian0 This is how it looks when creating it at the slab face with default settings:
![image](https://user-images.githubusercontent.com/19669673/83969297-8584f000-a8cf-11ea-984f-935b8aad5c3c.png)
So it should probably just start at the bottom of the face regardless of which face it is

**Comment by MCrafterzz** [comment]
@ranjian0 
![image](https://user-images.githubusercontent.com/19669673/84770453-de433f80-afd7-11ea-80f6-0916e5fc6fc9.png)
Apparently it isn't solved...
Also how about making it so that the offset is relative to the ground level so a offset of 0 0 is at the ground level? That would make more sence imo

**Comment by MCrafterzz** [comment]
Balconies generate at the correct position though
