### ISSUE TITLE
Better default values for roofs

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#113]
Increasing the default values for thickness and outset would be nice as they are so small that you hardly see them.

**Comment by MCrafterzz** [comment]
Also I didn't know where to post this: I really like your tool, thank you SO much for creating it! It's super useful and I'm looking forward to seeing how it evolves!

**Comment by ranjian0** [comment]
> Also I didn't know where to post this: I really like your tool, thank you SO much for creating it! It's super useful and I'm looking forward to seeing how it evolves! Would be cool if you could create a discord!

Discord is great idea!

**Comment by ranjian0** [comment]
> Increasing the default values for thickness and outset would be nice as they are so small that you hardly see them.

Is this for all roofs or a specific one

**Comment by MCrafterzz** [comment]
> > Increasing the default values for thickness and outset would be nice as they are so small that you hardly see them.
> 
> Is this for all roofs or a specific one

For all of them but especially the flat one

**Comment by ranjian0** [comment]
This could be related to the size of your buildings. If you are creating huge buildings i.e large initial floorplans like 10X10, other settings will feel small.

Currently, all default values are meant to work well together. Adjusting some by huge margins will make the rest feel inappropriate.

Could this be the issue.

**Comment by MCrafterzz** [comment]
> This could be related to the size of your buildings. If you are creating huge buildings i.e large initial floorplans like 10X10, other settings will feel small.
> Currently, all default values are meant to work well together. Adjusting some by huge margins will make the rest feel inappropriate.
> Could this be the issue.

You were right :P
