### ISSUE TITLE
No responsing when adding roof if floor is circle.

### ISSUE THREAD

**Issue by Qomolangma888** [ranjian0/building_tool#122]
No responsing when adding roof if floor is circle.
![BuildingTools_bug_01](https://user-images.githubusercontent.com/31262886/84454805-2f78c980-ac8e-11ea-8d23-45512d505c4b.jpg)

**Comment by ranjian0** [comment]
Nice catch!

**Comment by ranjian0** [comment]
updated solution to a5f5f888093c6a4d2e6388045396744608dbd0d1
