### ISSUE TITLE
Creating floor plan on ground level / Not working

### ISSUE THREAD

**Issue by JakubPelka** [ranjian0/building_tool#123]
Hello! Great plugin! I'd like to present a small problem that I found, or maybe it is lack of skill.

I use BlenderGIS plugin to import terrain model to Blender. I use the same plugin to import shapefile with polygon/faces representing house footprint. 

If I import shapefile without receiving height information from terrain model - than plugin works and makes it possible to create a house with all features.

If I import shapefile with information about ground level (so houses are on terrain, but polygon/face is still flat as it was earlier) than plugin can't create floors and other features. 
What can be the main reason? Can you please fix it or tell me what could be the problem? If it is a flat terrain it is not a big problem, but in hilly one, it may be an issue.

I attach blend. file with my data. Green house layer is working, red one is not. I want to recreate buildings with height from reality (there is also raw-data on buildings heights and geometry).
[Example.zip](https://github.com/ranjian0/building_tool/files/4770613/Example.zip)

EDIT: Roof feature works with shapefiles imported with height from terrain. It is Add floor that is not working... After extruding polygon it is saying that for ex. balcony not working with non-rectangular n-gon. But it is just simple extrusion along Z axis. It is rectangular N-gon... i think.

**Comment by ranjian0** [comment]
Hi @JakubPelka. I have tested the example you have provided. The problem is that the polygons are not completely flat. A quick solution would be to scale the polygons along z by zero.

**Comment by JakubPelka** [comment]
Hi! I tested it. It is a kind of solution! 
Only challenge is that every face/poligon must be rescaled individually so it doesn't move up&down a lot. But it works! :)
