### ISSUE TITLE
Custom floorplan type

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#124]
**Is your feature request related to a problem? Please describe.**
Yes, in many cases it isn't really possible to create the floorplan you want with the existing tools, so you have to do it manually with edit mode. This works but I feel like it would be great if the tool had a better alternative.

**Describe the solution you'd like**
I've looked around blender to better understand the currently available tools to not reinvent the wheel and I think the poly path can be very useful for this goal. The current manual workflow is as following:

1. Go to edit mode
2. Create a new curve
3. Set curve type to poly
4. Set curve to 2D
5. Extrude points
6. Enable closed curve
7. Go to object mode
8. Convert curve to mesh
9. Go to edit mode
10. Select all vertices
11. Create a face (In many cases it works to create one large ngon but sometimes it doesn't and in those cases it takes even more time as multiple faces have to be manually created)

As you can see these are quite many steps for something that I'll do quite commonly. So my proposed workflow:
1. Press the new "Create Floorplan Outline" button, this will create a curve with the correct options, select it and change to edit mode (Bit unsure about changing to edit mode as that's inconsistent with the other buttons)
2. Extrude points
3. Go back to object mode
4. Create a new floorplan, choose the custom option and choose your curve. Then it would automatically convert that outline to a mesh.

4 steps instead of 11 would be a huge time-saver!

I believe that this addition would make the addon much more usable so let me know what you think @ranjian0 ! I'm willing to work on this and send a pr.

**Comment by Koopa1018** [comment]
Pardon me for asking, but: what is it that makes poly paths easier to shape than meshes?

**Comment by MCrafterzz** [comment]
> Pardon me for asking, but: what is it that makes poly paths easier to shape than meshes?

Could be personal preference but I find it easier to create a outline with a path rather than having to subdivide, duplicate vertixes etc to be able to extrude at the right place. This is especially true if you want to create a shape that's not made up of only squares.

**Comment by MCrafterzz** [comment]
Maybe it's a terrible idea but I thought it was worth seeing you opionions :shrug:

**Comment by ranjian0** [comment]
@MCrafterzz The workflow you have mentioned seems to be specifically suited to your preferences. It will be very unlikely for the addon to support all the steps you have outlined and still remain suitable and practical for a large audience.

The floorplan tool is not meant to be _the end all be all_. It exists simply to provide a quick and convinient workflow for most users. As you are well aware, `building tools` still works perfectly even if users decide to make their own floorplan.

That said, your comments still provide some useful information about how the floorplan tool can be improved. In particular, step no 4.

> 4. Create a new floorplan, choose the custom option and choose your curve. Then it would automatically convert that outline to a mesh.

Providing an option to create floorplans from a curve outline seems quite practical to me. But creating the curve and setting up appropriate context as in steps 1 - 3 is a burden that **should** fall on users. 

I completely agree with your last line:

> Like if you in the most cases manually edit the shape then what's the point of the floorplan tool?

But we must also be practical. The addon cannot support everyone's workflow. The best we can do is provide convenience to the most common/repetitive steps that users come across when modelling buildings.

> Maybe it's a terrible idea but I thought it was worth seeing you opionions :shrug:

**All ideas are welcome.**

**Comment by MCrafterzz** [comment]
> @MCrafterzz The workflow you have mentioned seems to be specifically suited to your preferences. It will be very unlikely for the addon to support all the steps you have outlined and still remain suitable and practical for a large audience.
> 
> The floorplan tool is not meant to be _the end all be all_. It exists simply to provide a quick and convinient workflow for most users. As you are well aware, `building tools` still works perfectly even if users decide to make their own floorplan.
> 
> That said, your comments still provide some useful information about how the floorplan tool can be improved. In particular, step no 4.
> 
> > 1. Create a new floorplan, choose the custom option and choose your curve. Then it would automatically convert that outline to a mesh.
> 
> Providing an option to create floorplans from a curve outline seems quite practical to me. But creating the curve and setting up appropriate context as in steps 1 - 3 is a burden that **should** fall on users.
> 
> I completely agree with your last line:
> 
> > Like if you in the most cases manually edit the shape then what's the point of the floorplan tool?
> 
> But we must also be practical. The addon cannot support everyone's workflow. The best we can do is provide convenience to the most common/repetitive steps that users come across when modelling buildings.
> 
> > Maybe it's a terrible idea but I thought it was worth seeing you opionions shrug
> 
> **All ideas are welcome.**

I didn't know you could extrude vertices but apparently you can so that's much better than the 5 extra steps to set up a curve. So instead of the original post I suggest a option to generate a floorplan from a outline. Maybe by using polygon triangulation?

**Comment by ranjian0** [comment]
> I didn't know you could extrude vertices but apparently you can so that's much better than the 5 extra steps to set up a curve. So instead of the original post I suggest a option to generate a floorplan from a vertex outline. Maybe by using polygon triangulation?

Yep, I believe this would be a good feature to implement. You should close this and create a new enhancement issue for it. I will add to 1.1 milestone. 

I am not quite sure about how it could be implemented, it may be obvious or extremely tricky depending on what we consider a valid floorplan.
