### ISSUE TITLE
Creating roofs with weird shape freezes editor

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#128]
**Describe the bug**
Adding a roof some some shapes makes editor freeze for ever until you close the program
https://streamable.com/0nkgql
It could be due to two of the vertices being quite close? Moving those two vertices from eachover prevents creating floors but creating a roof still freezes the program.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a complex ngon
2. Add floors
3. Add roof
4. See the editor freeze

**Expected behaviour**
- Either it should create a roof or it should give a error message

**Comment by ranjian0** [comment]
Which roof type?

**Comment by MCrafterzz** [comment]
> Which roof type?

Flat one but could be all of them.

**Comment by ranjian0** [comment]
Would you happen to have a blend file with the polygon in the video?

**Comment by MCrafterzz** [comment]
@ranjian0 I recreated it with a new polygon, I sent it to you in our discord chat

**Comment by ranjian0** [comment]
closed by a5f5f888093c6a4d2e6388045396744608dbd0d1
