### ISSUE TITLE
Railing Improvements

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#13]
The railing module has quite a number of pain points. I have seriously thought about just completely removing it. This issue is a list of things I would like to change/improve in the module but due to time constraints or burnout have not been able to tackle.

**These issues are not bugs in and of themselves, but they are tricky to solve, make the module less usable and are usually the source of most bugs**

1. Its **Ugly**. All railings are blocky. My plan is to have some set of profiles that a user can select.

2. A lot of z-buffer fighting occurs in the geometry made by railing module. Adding margins everywhere this happens makes the code horrific. Look out for variables such as **pad** or **pinch** in the module. 

3. When using the **fill type posts**, there is a lot of non-uniformity in how the posts are distributed when the face being operated has _convex_ vertices. The reason for this deserves an entire blog post but in short, I don't like it.

4. The **expand walls** property. This is a hack solution to a problem closely related to No. 3.
Again, I don't like it.

**Comment by ranjian0** [comment]
Solved issues 3 and 4. 
ff4f2caa4361876228697af94182f9ae2aae1f6d for 3
72c8a65b15111f302be3a1818cdb09a1b6b26e29 for 4

**Comment by ranjian0** [comment]
After struggling with this for a couple of months, it seems the only way to manage complexity is to use railing as part of other modules such as balcony and stairs only. Implementing tools for a generic railing system has too many problems/edge cases.

`Balcony` and `Stairs ` modules have disabled as I work on this.

**Comment by luckykadam** [comment]
@ranjian0 Which branch are you working on?
I would be gald to take some load off you.

**Comment by ranjian0** [comment]
I am currently working in the `dev` branch, but it is a mess with ideas all over the place. If you still wanna, I am doing railing for balconies, see what you can get done for stairs. 

Feel free to try out many ideas, and share in this issue. Railing for stairs can get out of hand quickly. You can look at the 2.79 addon version to see how I did things then and learn from my mistakes.

**Comment by ranjian0** [comment]
After new railing system #49, closing this issue.
New issues will be created to address improvements to be made to the new system.
