### ISSUE TITLE
MacOS version is required please, all Blender addon's have MacOS versions. We missing out.

### ISSUE THREAD

**Issue by Mecdot** [ranjian0/building_tool#131]
MacOS version is required please, all Blender addon's have MacOS versions. We missing out.

**Expected behaviour**
all Blender addon's have MacOS versions

**Screenshots**
Identical to windows

**Desktop (please complete the following information):**
MacOS is required

**Additional context**
MacOS uses are missing out on this great needed addon

**Comment by ranjian0** [comment]
The addon should work in macOS!

**Comment by ranjian0** [comment]
closed as invalid
