### ISSUE TITLE
Another roof creation crash

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#135]
Things crash a lot :C

Todays crash is another roof one. To replicate create the following shape:
![image](https://user-images.githubusercontent.com/19669673/85265473-9c504880-b472-11ea-96fa-05bcd507fe8b.png)

Random floorplan, seed 1 and extension amount set to 4

- Add floors
- Add roof
- See it crash

**Comment by ranjian0** [comment]
confirmed.

Roof plane generation is a huge pain. Related to #128, #122.

**Comment by ranjian0** [comment]
closed by 620ac2f1a38f09d0f39e03cd9ec8d83ac1e4b6c0 and aa4692a01f9325783dc4275b2a798eb4df568c67
