### ISSUE TITLE
H shaped floor plans

### ISSUE THREAD

**Issue by doginthehole** [ranjian0/building_tool#138]
When trying to create an H shaped floorplan the tails are not properly aligned to the respective edge and do not extrude correctly. 

![image](https://user-images.githubusercontent.com/8890941/85954209-cfe41480-b943-11ea-8671-e73b153483cd.png)

**Comment by ranjian0** [comment]
Are you using building tool from release or master branch?

**Comment by doginthehole** [comment]
Build tool with blender 2.83

**Comment by ranjian0** [comment]
I mean, did you download from the releases page or from github master branch??

**Comment by doginthehole** [comment]
woops, I meant built version from release page

**Comment by ranjian0** [comment]
Ok, I have fixed this issue in 365091f2c4ce14f63b0fa08d3eecdbea2a456e71, but its not in the release yet. I will update release tomorrow. Currently, the script used for making releases is not working properly as mentioned in #137.

**Comment by ranjian0** [comment]
Please close the issue since it was already fixed.

**Comment by doginthehole** [comment]
thank you very much :)
