### ISSUE TITLE
I can't find building tools after installing the addon ???

### ISSUE THREAD

**Issue by Qomolangma888** [ranjian0/building_tool#139]
From 2020-06-26, when i use blender 2.9 alpha everyday built version, i can't find building tools after installing the addon ?
Then i install the addon under Blender 2.83.1 LTS, i also can't find it?
I hope authors can solve the problem, thank you very much.

**Comment by xan2622** [comment]
Hi.

I have just downloaded the latest Blender 2.90 (Daily Build) version and I just installed the addon without any problem. It works fine here. I guess you haven't installed it properly.

Follow these installation instructions: https://github.com/ranjian0/building_tool#installation
1. Just **download the ZIP file** but do not extract it. 
2. Then, in Blender, go to **Edit > Preferences > Addons** 
3. **Click on the "_Install..._" button** and just select the ZIP file
4. **Activate the addon** by ticking its checkbox in Preferences > Addons
5. You will notice a new "Building Tools" tab in the N panel (on the right side of your viewport)

**Comment by MCrafterzz** [comment]
Or do you mean installing it from source? Because in that case you can download as zip and then install that.

**Comment by Qomolangma888** [comment]
I find the solution. Unzip the downloaded file then Copy the "btool" folder to Blender Addons directory.
Thank you very much!

**Comment by MCrafterzz** [comment]
@Qomolangma888 glad you solved it :D please close this issue

**Comment by ranjian0** [comment]
> I find the solution. Unzip the downloaded file then Copy the "btool" folder to Blender Addons directory.
> Thank you very much!

@Qomolangma888 
Currently, downloading zip from github `master` branch will not work when you try to install in blender. Folder structure changed after I added testing. Always use zips from the releases page on the repo website.
