### ISSUE TITLE
feature request: vortex groups

### ISSUE THREAD

**Issue by frankyifei** [ranjian0/building_tool#16]
if it supports creating vortex groups for each component of the building, it could be more convenient for material setting. Creating vortex groups manually is very slow for each component after completion of the building.

**Comment by ranjian0** [comment]
I am currently working on this but using face maps instead. 
I will keep this issue open until I have merged the features into master. Hopefully by the end of this
month I will have things working.

Cheers.

**Comment by frankyifei** [comment]
Thank you. You are awesome！

**Comment by ranjian0** [comment]
#17 
Still more work to do but a start

**Comment by ranjian0** [comment]
Commit ef439d23bc459bde1b4da3ab6b4c2e22994f81d7
Allows user to easily add materials to active facemaps. I can now consider this issue closed.

Cheers.
