### ISSUE TITLE
Adding glass to windows causes bizzare behavior in  Blender 2.81

### ISSUE THREAD

**Issue by cowdawg** [ranjian0/building_tool#18]
create floor plan --> set to 8 x 10 size -->edit mode --> add floor --> select wall --> add window
---> array elements (set count to 8) --> fill type --> glass
![image](https://user-images.githubusercontent.com/1289105/70391726-40c2df80-19a6-11ea-83ad-9c98a9acf7db.png)

**Comment by ranjian0** [comment]
Not able to duplicate this.
Could you please provide a screenshot of all your window properties.

In any case, this is probably caused by setting extremely high or low values for properties.

**Comment by GabrielGB1999** [comment]
happens the same to me. it occurs sporadically and leaves a corrupted mesh instead of an extruded one

**Comment by ranjian0** [comment]
Please post a screen shot.

**Comment by ranjian0** [comment]
Not able to reproduce using latest 2.80 release. Feel free to reopen issue.
