### ISSUE TITLE
Error installing addon

### ISSUE THREAD

**Issue by egycno** [ranjian0/building_tool#19]
When I install building_tool-0.9.6 I get
![image](https://user-images.githubusercontent.com/31624258/73700416-5cdbb800-469b-11ea-949f-221defef6645.png)

and when I install building_tool-0.9.7 (master) I get

![image](https://user-images.githubusercontent.com/31624258/73700562-b3e18d00-469b-11ea-8ce7-887f668a054a.png)
 how can i fix it ?

**Comment by ranjian0** [comment]
Fixed by a02e468f907c2e5e1d0913da44c9c0c33dfd3dc9

**Comment by ranjian0** [comment]
Please try installing the new Blender 2.80 release dated today [06/06/2020]. Thanks for opening this issue. Cheers.
