### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by HiroshisLounge** [ranjian0/building_tool#20]
I downloaded the current and past files and none of them work in 2.80 or 2.79.

I tried importing by going to preferences and importing the .zip, I tried extracting and putting it in the addons folder in the blender files, etc...

I get the same issue as #10 and I tried importing the v0.9.3. release into blender 2.80 but it didnt work

**Comment by ranjian0** [comment]
Did some testing and the zip file from the releases page has the name `building_tool-0.9.7-rc1` which blender doesn't seem to be happy with. Renaming the zip file to `building_tool` fixes the installation problem.

I will keep this issue open in the as I try to resolve this issue.

**Comment by ranjian0** [comment]
**Dirty fix for now.**
_Tags_ now use underscores as in `building_tool-0_9_7_rc2` instead of `building_tool-0.9.7.rc2`.
This should hopefully prevent new users from been frustrated with installation.

**Comment by HiroshisLounge** [comment]
i renamed it and tried importing the zip thru blender and it didnt work so i unzipped it and put it directly into the addons folder and it works now

thx bro

**Comment by ranjian0** [comment]
A [user](https://blenderartists.org/t/building-tools/1114888/36) on BlenderArtists using the 2.79 addon release was also suffering from the same issue.

Anyone installing the 2.79 release should make sure to rename the zip file.

**Comment by ranjian0** [comment]
The proper solution for this is to extract the releases zip file eg. `building_tool-v1.0.0-alpha.zip` which will produce a folder `building_tool-v1.0.0-alpha`. 

From here, rename the folder to `building_tool`. You can drop this folder into the addons directory in blender or re-zip it and install in blender from the addon preferences.
