### ISSUE TITLE
Unable to apply textures to the model.

### ISSUE THREAD

**Issue by Raavtube** [ranjian0/building_tool#22]
I am using Blender 2.81 and when I use this to create the building it works fine. But when I use the inboard Material Tools it messes up. I am in Edit mode, I select the "Walls" from the scroll list, then I click the Select, then it selects the mesh, I then select my texture, [THIS ](https://cc0textures.com/view?tex=Bricks22)is the texture I am using. I select it, then I click assign. But it doesn't assign the texture. This works with color and emission textures but not with image textures??? How can I fix this?

**Comment by ranjian0** [comment]
I am assuming that your texture is already linked to a material, if so, then after you select the `Walls` from the material list, you need to UV **unwrap** the selected faces. `Cube Projection` works pretty nice for the walls. In `edit mode` press `U` and then select `Cube Projection`.

Other features like doors and windows should work well with normal unwrap. Roofs may need a bit of tweaking.

Hope this fixes it.
Cheers.

**Comment by ranjian0** [comment]
PS: Once the faces are selected, you only need to select a material under `Active Face Map Material`. **Do Not** click `Assign` unless you want to add/remove more faces to the `Walls`.

**Comment by ranjian0** [comment]
# Example setup with your brick textures

## Viewport
![image](https://i.imgur.com/1CYl2VK.png)

## UVs
![image](https://i.imgur.com/WTejUhi.png)

## Material Nodes
![image](https://i.imgur.com/eOkMiwy.png)
