### ISSUE TITLE
Crash: Slab thickness 0

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#26]
Steps to reproduce:
1. Create Floorplan
2. Go into edit mode
3. Select a face
4. Add Floors
5. In operation properties, set Slab Thickness to 0

Note: This happens only when some faces are selected.

**Comment by luckykadam** [comment]
While debugging the issue, I encountered a few inconsistencies:
1. Using Add Floors with a face selected, deletes the originally selected face. Whereas, when Add Floors is used without any face selected, no faces are deleted.
<img width="679" alt="Screenshot 2020-03-10 at 10 10 18 PM" src="https://user-images.githubusercontent.com/11018027/76337269-1d009400-631d-11ea-85a2-b5d6e6295c7d.png">
<img width="675" alt="Screenshot 2020-03-10 at 10 10 03 PM" src="https://user-images.githubusercontent.com/11018027/76337292-2689fc00-631d-11ea-99d7-c0a7ac6f242d.png">


2. When Slab Thickness is 0, strangely a slab is added to the bottom floor in downward direction.
<img width="682" alt="Screenshot 2020-03-10 at 10 11 01 PM" src="https://user-images.githubusercontent.com/11018027/76337373-44eff780-631d-11ea-834c-f9cb638e3aaa.png">

Trying to understand the expected behavior in all these case.
@ranjian0 can you please help?

**Comment by ranjian0** [comment]
The floors can be created one of two ways.

1. Floors can be created from the result of Create Floorplan operator. In this case no selection is necessary.

2. A floor can also be created by selecting the top face/roof of an existing building. Here a selection is required, and the face is deleted afterwards.

The bottom face of a building will most likely never be seen, so perhaps both use cases should delete afterwards.

**Comment by ranjian0** [comment]
No. 2 is a bug. Thickness of 0 should remove the slab completely.
