### ISSUE TITLE
Validation: Add Window properties

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#29]
1. Proper validation of `Add Window` properties.
2. Consistent `Offset` properties. `Offset` values relative to wall.

![](https://user-images.githubusercontent.com/11018027/75988368-76c91e80-5f17-11ea-9371-d07e4b6d27ec.png)

**Comment by ranjian0** [comment]
This is a general issue that occurs anywhere `Size & Offset` is used. It is wise to come up with a solution that can be reapplied to other cases.
