### ISSUE TITLE
Size & Offset: Expanding horizontal size to maximum with arrayed elements causes geometry issues

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#32]
This is probably an issue with how insets are created. Most likely culprit is function `inset_face_with_scale_offset` in `util_mesh.py`.

![Imgur](https://i.imgur.com/XuRmIq0.png)

- Some windows disappear.
- Others expand vertically

**Comment by luckykadam** [comment]
@ranjian0 assign this to me.

**Comment by luckykadam** [comment]
The root cuase of this issue is the inability to apply `Add Window` operation to n-gons. This particular issue occurs when the operator is applied to the face which contains an edge earlier subdivided.
I suggest to solve for support of n-gons which are rectangles with sudivided edges. A general solution would solve this issue for every operator.

**Comment by ranjian0** [comment]
Issue #30 already got me thinking about this. The function `inset_face_with_scale_offset` subdivides a quad so that all adjacent faces are rectangular.

![Imgur](https://i.imgur.com/CyyG6mM.png)

Faces 1,2,3,4 in the above, become also good candidates for another inset. This in spite of the fact that 1 & 3 are already n-gons. The function achieves this by always starting with vertical subdivisions.

![Imgur](https://i.imgur.com/P8DXq9i.png)

Faces 1-10 would also be good candidates for another inset. So long as you start first with vertical subdivisions. This whole idea hinges on the horizontal edges being unsubdivided which is the case for this particular issue.

Array elements fail because the vertical edges collapse into one another.

![Imgur](https://i.imgur.com/2Xi5vtx.png)

I am not sure, but I think I had set the maximum size for X in the SizeOffsetProperty as `0.9999` for this exact issue. Probably did a clamp in the code.

As for the n-gon issue, if you can find a general solution, I am all for it. But I think as long as tools in the addon are consistent and limits set, the problem should be avoidable.

**Comment by ranjian0** [comment]
Just tested clamping and adding

```python
value = (clamp(value[0], 0.1, self.parent_dimensions.x - 0.001), value[1])
```
in the SizeOffsetProperty `set_size` method fixes this.
