### ISSUE TITLE
Inconsistent facemaps for door and window

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#42]
Face maps for door and window frames not consistent after #41

**Comment by luckykadam** [comment]
@ranjian0 Can you attach an image to show the inconsistency.
PS: I dont know how to check it.

**Comment by ranjian0** [comment]
For instance, after creating a window, the face maps for the window frames don't point to valid faces

This is what I get:
![Imgur](https://i.imgur.com/7tPBwRy.png)

This is what it should be:
![Imgur](https://i.imgur.com/93J8mh5.png)

This happens for `WIndow`, `Door` and `Multidoor`.

**Comment by ranjian0** [comment]
fixed by #41
