### ISSUE TITLE
Stair bottom types

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#48]
Bottom of stairs can be of mainly four types:
1. filled (current behaviour)
<img src="https://user-images.githubusercontent.com/11018027/78907597-8996bc00-7a9e-11ea-90a5-396c8e3de8c0.jpg" height=256 width=256>
2. slope
<img src="https://user-images.githubusercontent.com/11018027/78907750-b9de5a80-7a9e-11ea-94b7-11dbf5ddb7ae.jpg" height=256 width=256>
3. blocked
<img src="https://user-images.githubusercontent.com/11018027/78907640-99160500-7a9e-11ea-8f5d-f0b12fa7a27d.jpg" height=256 width=256>
4. separated
<img src="https://user-images.githubusercontent.com/11018027/78907628-93b8ba80-7a9e-11ea-8e47-5b5acdf8dd37.jpg" height=256 width=256>

**Comment by ranjian0** [comment]
types 3 and 4 seem more suited to interiors.

**Comment by ranjian0** [comment]
closed by #52
