### ISSUE TITLE
Balcony Railing Issues

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#51]
![Imgur](https://i.imgur.com/VV0XaOS.png)

- [x] 1. When balcony is created on slab face, small gap is left between the railing and building walls.

- [x] 2.The top rails intersect with the corner posts. May cause z-buffer fighting.

- [x] 3. The open option for balcony railing does nothing, This option is meant to facilitate creating balconies on the corners of buildings. I suggest removing the option in favour of a better workflow.

### Rails and Wall Fill types
![Imgur](https://i.imgur.com/LcqfrFp.png)

- [x] 4. The size of the rails in railing fill and wall width in the wall fill should be clamped to less than or equal to the corner post width.

___

- [x] 5. Material face maps have incorrect names and invalid/no selection for post, wall and rail fill.

**Comment by luckykadam** [comment]
The gap between railing and building wall (when creating balcony from slab) is solved by Depth Offset field in Add Balcony and Add Stairs operators. checkout #52

**Comment by ranjian0** [comment]
No. 2 fixed by 6c1a6dbb6f6ef30dc4ce659892ffa8b7dd9f5abe
