### ISSUE TITLE
Roof: gable roof not working for rotated plane

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#55]
Gable roof works only for plane aligned with x-y axis.

<img width="823" alt="Screenshot 2020-04-19 at 12 20 27 PM" src="https://user-images.githubusercontent.com/11018027/79681475-2b08d500-8238-11ea-8658-e14b43af2e1f.png">

**Comment by ranjian0** [comment]
Seems to work for me.

![Imgur](https://i.imgur.com/Tiq08tm.png)
