### ISSUE TITLE
Railing: Corner posts issue

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#56]
Corner posts rotated when balcony/stair added to rotated plane.

<img width="756" alt="Screenshot 2020-04-19 at 12 40 50 PM" src="https://user-images.githubusercontent.com/11018027/79681837-04986900-823b-11ea-86e8-4d652a3b46f3.png">

**Comment by ranjian0** [comment]
Seems to be working for me.

![Imgur](https://i.imgur.com/lKrmmyc.png)

**Comment by luckykadam** [comment]
I think you have rotated the whole object.
Here are the steps to recreate:
1. Create a floor
2. Tab to enter edit mode. Select all. Rotate around z axis.
3. Add balcony to face

**Comment by ranjian0** [comment]
I did. Not sure why a user would rotate in edit mode, but this is a bug either way. Will try and solve for #55. This one is yours.

**Comment by luckykadam** [comment]
fixed by #65
