### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [ranjian0/building_tool#6]
Hello, under what license is this project released under ? I would like to learn Blender scripting from it. Thank-you.

**Comment by ranjian0** [comment]
Just created a pull request with MIT License, which is what I will use for the project.
Feel free to play with the source code and learn from it.

**NB.**
 Blender has a very unique scripting API. There are very strong restrictions which makes it
difficult to implement features that are unsupported. This generally means that it's is up to the
addon developer to decide what to do when the API just isn't enough. In an addon like this, I have
had to make such decisions, so beware. Some of the things I do are not standard/best practise.
Cheers.
