### ISSUE TITLE
Property Resetting

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#63]
Properties once adjusted remain that way even when the user starts creating a different element.
This may cause issues depending on the current context. The most affected properties by this are `Size and Offset`.

It would be better to reset all properties to their default when a user begins a new operation.

**Comment by luckykadam** [comment]
The property are persistence for the same operation only, but not for different operations.
I think its actually good that this happens.
For example: If someone adds a door again, then I they would want the same door dimensions by default.

**Comment by ranjian0** [comment]
> The property are persistence for the same operation only, but not for different operations.
> I think its actually good that this happens.
> For example: If someone adds a door again, then I they would want the same door dimensions by default.

Maybe I can show you a few cases when this can destroy users natural workflow. But I think its mostly an issue with the size and offset options.

**Comment by ranjian0** [comment]
Can't remember what I was going to show! Closing this
