### ISSUE TITLE
Floor: partial add floor

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#66]
Unexpected behaviour when adding floor on some (not all) faces, when `Add Slab` is True.

<img width="749" alt="Screenshot 2020-04-20 at 7 14 54 PM" src="https://user-images.githubusercontent.com/11018027/79758825-85d72500-833b-11ea-9d5d-d1894211dde6.png">
<img width="617" alt="Screenshot 2020-04-20 at 7 15 12 PM" src="https://user-images.githubusercontent.com/11018027/79758834-88397f00-833b-11ea-8bf0-370d3f1a6385.png">

**Comment by ranjian0** [comment]
I suspect this is due to the fact that slabs are created by first extruding and then doing a negative inset. If the operations can be reversed and still produce the same result, it would work.

**Comment by ranjian0** [comment]
Fixed by #73
