### ISSUE TITLE
Z buffer fighting when railing wall width is zero

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#72]
Setting a railing wall width of zero causes z-buffer fighting artefacts because there are two faces with no distace between them.

![Imgur](https://i.imgur.com/8AYuzZr.png)

**Comment by luckykadam** [comment]
easily solvable by putting a lower limit on wall width

**Comment by ranjian0** [comment]
Can I assign you

**Comment by ranjian0** [comment]
Fixed by 5e5e7ff3e58f9574886006b3e52883af94213386
