### ISSUE TITLE
Add Floor: behavior

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#75]
I would like to suggest a change in behavior of `Add Floors` operator on partially selected faces.

When adding floor on incomplete selection of top faces:

<img width="300" alt="Screenshot 2020-04-23 at 8 05 59 PM" src="https://user-images.githubusercontent.com/11018027/80112321-9affbe00-859e-11ea-8513-3114275d2a6c.png">

Current behavior:

<img width="300" alt="Screenshot 2020-04-23 at 8 06 07 PM" src="https://user-images.githubusercontent.com/11018027/80112352-a357f900-859e-11ea-8e72-be51127f525d.png">

Suggested behavior:

<img width="300" alt="Screenshot 2020-04-23 at 8 07 41 PM" src="https://user-images.githubusercontent.com/11018027/80112360-a521bc80-859e-11ea-8cc7-eed59ce3fd43.png">

In actual buildings slab is added to the complete top rather than just the ones will further floors. It would be great to have the detail here as well.

**Comment by luckykadam** [comment]
@ranjian0 what do you think?

**Comment by ranjian0** [comment]
>In actual buildings slab is added to the complete top rather than just the ones will further floors. It would be great to have the detail here as well.

This is true. 
I think its a more realistic behaviour. Feel free to submit a pull request for it.

**Comment by luckykadam** [comment]
closed by #76
