### ISSUE TITLE
Add Floor: Unexpected results

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#77]
Adding floor to complex geometry gives unexpected results.

<img width="400" alt="Screenshot 2020-04-23 at 10 38 05 PM" src="https://user-images.githubusercontent.com/11018027/80131528-0013dd80-85b8-11ea-8cd3-c9e57bebc1c8.png">
<img width="400" alt="Screenshot 2020-04-23 at 10 38 08 PM" src="https://user-images.githubusercontent.com/11018027/80131547-0609be80-85b8-11ea-9cb4-11f6f9fc2ece.png">

**Comment by ranjian0** [comment]
That doesn't seem right. How did you create that floorplan??

**Comment by luckykadam** [comment]
create floor with type=random and seed=2

**Comment by luckykadam** [comment]
raised a PR against this. #78
