### ISSUE TITLE
Roof: geometry issue

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#79]
Geometry issue when adding roof to a face, with center not at (0,0,0).

<img width="687" alt="Screenshot 2020-04-24 at 6 15 04 PM" src="https://user-images.githubusercontent.com/11018027/80214632-cf37b500-8658-11ea-8e9a-d63842825ff2.png">

<img width="845" alt="Screenshot 2020-04-24 at 6 15 12 PM" src="https://user-images.githubusercontent.com/11018027/80214604-c5ae4d00-8658-11ea-94fa-ef1afdaddea2.png">

I suspect the cause to be: https://github.com/ranjian0/building_tool/blob/8cf5d6a03349b2d326debe1b8f814eb3b6495565/core/roof/roof_types.py#L217

**Comment by ranjian0** [comment]
Fixed by fc6a97ef83e5cbf2ccacf66e2a26916bf3a4cbed
