### ISSUE TITLE
Any plans for roofs?

### ISSUE THREAD

**Issue by nafergo** [ranjian0/building_tool#8]
This addon looks realy great :)
Do you have any plans for expanding roofs? And custom roof types?

**Comment by ranjian0** [comment]
Roofs are one of the more complex parts in the addon. That said, I find it unreasonable to provide more
options than those that currently exist. In fact, I still don't consider the roof tools stable, and in most of my tests, they fail with even the slightest agitation. 

If I ever take the time to expand roofs, it will not be in the near future. I will, however, work to ensure
that the few tools that are available work as expected.
