### ISSUE TITLE
Door: allow negative frame depth

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#82]
1. Many times, door/window frame is deeper than the wall. Currently we don't support that. We only support frame to extrude (with +ive frame depth) but never intrude.
2. Also, I currently door depth is independent of frame. I think it would be better to move door (according to door depth) relative to the frame.

**Comment by ranjian0** [comment]
Can you show some images of this??

**Comment by luckykadam** [comment]
<img width="300" alt="Screenshot 2020-04-25 at 6 00 05 PM" src="https://user-images.githubusercontent.com/11018027/80279985-9a8e3100-871e-11ea-8cb9-f2d4b8d2d9c4.png">

<img width="400" alt="Screenshot 2020-04-25 at 5 55 49 PM" src="https://user-images.githubusercontent.com/11018027/80279904-02904780-871e-11ea-94e1-edbdcea05832.png">

**Comment by ranjian0** [comment]
Shouldn't be too hard to add this.
