### ISSUE TITLE
Any plans for interior generation?

### ISSUE THREAD

**Issue by BradBath** [ranjian0/building_tool#88]
Is there any plan to make it so this tool can generate interior walls? This tool is perfect for creating interiors but it'll be perfect for me if also generated interior walls since the game I'm making requires buildings with interiors and currently using archipack is quite slow and would LOVE something that would just let me quickly generate buildings with interiors.

**Comment by ranjian0** [comment]
Unfortunately, the plan for building tools is to only support creation of exteriors.
