### ISSUE TITLE
v1.0.0-alpha.2 enable 2.83 error

### ISSUE THREAD

**Issue by xiantuan** [ranjian0/building_tool#93]
Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'building_tool-1'

**Comment by luckykadam** [comment]
hi @xiantuan . Please follow installation installation instructions at: https://ranjian0.github.io/building_tool/ and use the download link in that page.

This should solve the issue. You can read more about the issue at: https://github.com/ranjian0/building_tool/issues/20

**Comment by ranjian0** [comment]
> 
> 
> hi @xiantuan . Please follow installation installation instructions at: https://ranjian0.github.io/building_tool/ and use the download link in that page.
> 
> This should solve the issue. You can read more about the issue at: #20

We should probably update the main README file for install instructions

**Comment by luckykadam** [comment]
> We should probably update the main README file for install instructions

done.
