### ISSUE TITLE
Support for the latest blender version

### ISSUE THREAD

**Issue by dareksob** [ranjian0/building_tool#94]
This addon don't work with the latest blender version 2.82. Any plans for compatibility?

**Comment by luckykadam** [comment]
hi @dareksob . As far as I know, it compatible with blender 2.82.
Please explain the issue you have.

**Comment by DemonXD** [comment]
blender version: 2.82a,
addon version: 1.0.0
ERROR:
![image](https://user-images.githubusercontent.com/12723424/82796651-769e4680-9ea8-11ea-8af5-5f54ce863d98.png)

**Comment by luckykadam** [comment]
@dareksob Please refer to #93
