### ISSUE TITLE
Corrugated/beveled walls request label:enhancement 

### ISSUE THREAD

**Issue by ironhands79** [ranjian0/building_tool#97]
Was thinking of something like this, a subdivide and move to create a bevel or corrugation effect.  This could allow for quick creation of stacks of cargo shipping containers, or a shanty town.

In addition, an option for vertical framing could be very useful in general, just an edge on the wall corners that more or less sticks out as far as the floor slabs.

![crate](https://user-images.githubusercontent.com/65862699/82834805-359a3800-9e90-11ea-91fa-b7e9c601c9a7.png)

![Container-Bespoke-Homes2-960x600](https://user-images.githubusercontent.com/65862699/82835168-397a8a00-9e91-11ea-8e3c-842a35552abc.jpg)
![stock-photo-business-cargo-port-cargo-container-import-trade-delivery-shipment-export-3638e817-b982-4156-bf01-18490a4beaad](https://user-images.githubusercontent.com/65862699/82835176-3f706b00-9e91-11ea-847e-8b4304cd79c3.jpg)

**Comment by luckykadam** [comment]
Hi @ironhands79 ,

This container effect can be achieve by displacement mapping.
Because Building Tools workflow is heavily dependent on geometry, we want to minimize destructive geometric operations.
