### ISSUE TITLE
Easy Construction Of Release Archives

### ISSUE THREAD

**Issue by ldo** [ranjian0/building_tool#99]
Let me suggest adding the enclosed script for automatically constructing your release archives. This leaves out unnecessary stuff like `.gitignore`, and takes file timestamps and contents from the commit history, so that two people making archives for the same commit from their own copies of the repo will end up with bit-for-bit-identical archive files.

This only does zipfiles—do you really need `.tar.gz` files as well?

    #!/usr/bin/python3
    #+
    # Generate an addon release archive. For repeatability, the timestamp
    # and contents for each file are taken from the last commit affecting
    # that file.
    #
    # This script takes an arg identifying a specific commit (e.g. a tag)
    # from which to generate the archive. For example, the command
    #
    #     ./make-dist v1.0
    #
    # will make an archive for the commit tagged “v1.0” (assuming it exists).
    # This tag name will also be included in the created archive name.
    #-

    import sys
    import os
    import time
    import subprocess
    import zipfile
    import getopt

    def git(*args) :
        # convenience routine for simplifying git command calls.
        return \
            subprocess.check_output(("git",) + args)
    #end git

    opts, args = getopt.getopt \
      (
        sys.argv[1:],
        "",
        []
      )
    if len(args) != 1 :
        raise getopt.GetoptError("expecting exactly one arg, the tag to build a release for")
    #end if
    upto = args[0]
    earliest = git("rev-list", "--reverse", upto).split(b"\n")[0].strip().decode()

    basename = "building_tool"
    outfilename = "%s-%s.zip" % (basename, upto)
    out = zipfile.ZipFile(outfilename, "x")
    for item in \
        (
            "__init__.py",
            "LICENSE",
            "README.md",
            "TODO",
            "core/",
            "docs/",
            "utils/",
        ) \
    :
        if item.endswith("/") :
            items = sorted \
              (
                set
                  (
                    line.rsplit("\t", 1)[1]
                    for line in git("log", "--raw", item).decode().split("\n")
                    if line.startswith(":")
                  )
              )
              # every file that has ever existed in this directory in the commit history
        else :
            items = (item,)
        #end if
        for filename in items :
            info = \
                git("log", "--format=%ct:%H", "-n1", "%s..%s" % (earliest, upto), "--", filename) \
                .strip()
            if info != b"" :
                item = zipfile.ZipInfo()
                item.filename = "/".join((basename, filename))
                item.external_attr = 0o100644 << 16
                item.compress_type = zipfile.ZIP_DEFLATED
                timestamp, commit_hash = info.split(b":")
                timestamp = int(timestamp)
                info = git("ls-tree", commit_hash, filename).strip()
            #end if
            if info != b"" :
                object_hash = info.split(b"\t")[0].split(b" ")[2].decode()
                object_contents = git("show", object_hash)
                item.date_time = time.gmtime(timestamp)[:6]
                out.writestr(item, object_contents)
            #end if
        #end for
    #end for
    out.close()

    sys.stdout.write("created archive: %s\n" % outfilename)

This is based on the `make-dist` script I did for my adaptation of the [spaceship_generator](https://github.com/ldo/blender_spaceship_generator) addon.

**Comment by ranjian0** [comment]
Would you mind making a pull request for this? Seems like a huge time save.
Also, No! We do not need `tar.gz`.

**Comment by ranjian0** [comment]
@ldo We have been having issues with Github releases as you can see from the pinned issue #20. I had to delete all releases yesterday to prevent users from getting them.
I just downloaded the `spaceship_generator` addon from your repository and install works without any issues. This will be a huge help!

**Comment by ldo** [comment]
I’m not really keen on maintaining my own fork of your code. I’d prefer to keep things centralized.

[Here](https://github.com/ranjian0/building_tool/files/4685782/Add-make-dist-script-for-repeatable-construction-of-.patch.txt) is the same thing in a form that can be applied with `git-apply`, if that’s more convenient.

**Comment by ranjian0** [comment]
Pushed new branch `feature-release-archives` that implements this. Will merge in 1.1.

**Comment by ldo** [comment]
Just a note that you shouldn’t need to wait for a release before using this script. You should be able to use it to (re)generate existing releases.

**Comment by ranjian0** [comment]
closed by 9eb99292
